# Generated by Django 6.1.1 on 2026-10-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShelterPoint',
            fields=[
                ('id', models.CharField(help_text='Public identifier (e.g. OZO-6D94271C9708)', max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Miejsce ochronne', help_text='Object name', max_length=120)),
                ('object_type', models.CharField(default='Obiekt ochrony ludności', help_text='Type of protection facility', max_length=120)),
                ('voivodeship', models.CharField(db_index=True, help_text='Województwo (e.g. dolnośląskie)', max_length=32)),
                ('county', models.CharField(db_index=True, help_text='Powiat (e.g. Wrocław, pow. nyski)', max_length=64)),
                ('commune', models.CharField(db_index=True, help_text='Gmina (e.g. Wrocław, Otmuchów)', max_length=64)),
                ('address', models.CharField(help_text='Street address / locality', max_length=255)),
                ('accessibility', models.CharField(db_index=True, help_text='Accessibility status (Całodobowa, Na żądanie, Określone godziny)', max_length=32)),
                ('latitude', models.FloatField(db_index=True, help_text='Latitude in WGS84 coordinate system')),
                ('longitude', models.FloatField(db_index=True, help_text='Longitude in WGS84 coordinate system')),
            ],
            options={
                'verbose_name': 'Punkt schronienia',
                'verbose_name_plural': 'Punkty schronienia',
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='idx_shelter_coords'), models.Index(fields=['voivodeship', 'county', 'commune'], name='idx_shelter_location')],
            },
        ),
    ]
